# Generated by Django 6.0.1 on 2026-03-16 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="메뉴명")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="메뉴 코드"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_menus",
                        to="permission.menucategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "1. 메뉴 카테고리",
                "verbose_name_plural": "1. 메뉴 카테고리 관리",
            },
        ),
        migrations.CreateModel(
            name="PermissionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("OWN", "본인 데이터만"),
                            ("DEPT", "소속 부서 데이터"),
                            ("ALL", "전사 데이터"),
                        ],
                        default="OWN",
                        max_length=10,
                        verbose_name="접근 범위",
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(default=True, verbose_name="조회 권한"),
                ),
                (
                    "can_create",
                    models.BooleanField(default=False, verbose_name="입력 권한"),
                ),
                (
                    "can_edit",
                    models.BooleanField(default=False, verbose_name="수정 권한"),
                ),
                (
                    "can_delete",
                    models.BooleanField(default=False, verbose_name="삭제/비활성 권한"),
                ),
                (
                    "can_approve",
                    models.BooleanField(default=False, verbose_name="승인/확정 권한"),
                ),
                (
                    "can_export",
                    models.BooleanField(default=False, verbose_name="엑셀 다운로드"),
                ),
                (
                    "view_sensitive",
                    models.BooleanField(
                        default=False, verbose_name="민감 정보(마스킹 해제)"
                    ),
                ),
                (
                    "can_view_log",
                    models.BooleanField(default=False, verbose_name="작업 로그 조회"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permission.menucategory",
                        verbose_name="대상 메뉴",
                    ),
                ),
            ],
            options={
                "verbose_name": "2. 세부 권한 항목",
                "verbose_name_plural": "2. 세부 권한 항목 설정",
                "unique_together": {
                    (
                        "menu",
                        "scope",
                        "can_view",
                        "can_create",
                        "can_edit",
                        "can_delete",
                        "can_approve",
                        "can_export",
                        "view_sensitive",
                        "can_view_log",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="역할명")),
                ("description", models.TextField(blank=True, verbose_name="역할 설명")),
                (
                    "is_admin_role",
                    models.BooleanField(default=False, verbose_name="관리자 역할 여부"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        to="permission.permissionitem", verbose_name="포함된 권한들"
                    ),
                ),
            ],
            options={
                "verbose_name": "3. 사용자 역할",
                "verbose_name_plural": "3. 사용자 역할 관리",
            },
        ),
    ]
