# Generated by Django 6.0.1 on 2026-05-06 04:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("permission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "emp_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="사원코드"
                    ),
                ),
                (
                    "emp_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="사원번호"
                    ),
                ),
                ("emp_nm", models.CharField(max_length=50, verbose_name="성명")),
                (
                    "emp_pos",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="직급"
                    ),
                ),
                (
                    "emp_type",
                    models.CharField(
                        choices=[
                            ("정규직", "정규직"),
                            ("계약직", "계약직"),
                            ("파트타임", "파트타임"),
                        ],
                        default="정규직",
                        max_length=30,
                        verbose_name="고용형태코드",
                    ),
                ),
                (
                    "emp_stat",
                    models.CharField(
                        choices=[
                            ("재직", "재직"),
                            ("휴직", "휴직"),
                            ("퇴직", "퇴직"),
                            ("정직", "정직"),
                        ],
                        default="재직",
                        max_length=30,
                        verbose_name="재직상태코드",
                    ),
                ),
                (
                    "emp_tel",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="연락처"
                    ),
                ),
                (
                    "emp_add",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="주소"
                    ),
                ),
                ("emp_rn", models.TextField(unique=True, verbose_name="주민등록번호")),
                ("emp_hire", models.DateField(verbose_name="입사일")),
                (
                    "emp_retire_dt",
                    models.DateField(blank=True, null=True, verbose_name="퇴사일"),
                ),
            ],
            options={
                "verbose_name": "사원 마스터",
                "verbose_name_plural": "사원 마스터",
                "db_table": "hr_employee",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="부서코드"
                    ),
                ),
                (
                    "dept_comp",
                    models.CharField(max_length=100, verbose_name="소속회사명"),
                ),
                ("dept_nm", models.CharField(max_length=50, verbose_name="부서명")),
                ("in_use", models.BooleanField(default=True, verbose_name="사용여부")),
                (
                    "parent_dept",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_dept_id",
                        help_text="부서 안에 소속된 부서의 경우 이 컬럼을 사용합니다.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_departments",
                        to="hr.department",
                        verbose_name="상위부서코드",
                    ),
                ),
            ],
            options={
                "verbose_name": "부서 마스터",
                "verbose_name_plural": "부서 마스터",
                "db_table": "hr_department",
            },
        ),
        migrations.CreateModel(
            name="EmployeeFinance",
            fields=[
                (
                    "emp",
                    models.OneToOneField(
                        db_column="emp_id",
                        help_text="사원 1:1 연결",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="finance",
                        serialize=False,
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
                (
                    "bank_nm",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="은행명"
                    ),
                ),
                (
                    "bank_acc_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="계좌번호"
                    ),
                ),
                (
                    "bank_holder",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="예금주"
                    ),
                ),
                (
                    "has_car",
                    models.BooleanField(default=False, verbose_name="본인차량여부"),
                ),
            ],
            options={
                "verbose_name": "사원 금융 정보",
                "verbose_name_plural": "사원 금융 정보",
                "db_table": "hr_employee_finance",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="dept",
            field=models.ForeignKey(
                db_column="dept_id",
                help_text="소속 부서 연결",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="hr.department",
                verbose_name="부서코드",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[("dst", "DST"), ("jsystem", "J-System")],
                        default="dst",
                        max_length=10,
                        verbose_name="소속 회사",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="가입 승인 여부"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="최근 접속 IP"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="permission.userrole",
                        verbose_name="권한 역할",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_account",
                        to="hr.employee",
                        verbose_name="연결 사원",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 계정",
                "verbose_name_plural": "사용자 계정",
                "db_table": "hr_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalAnnualLeave",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                (
                    "total_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="사용가능한연차(A)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        db_column="emp_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 연차 관리",
                "verbose_name_plural": "historical 연차 관리",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAttendanceLog",
            fields=[
                (
                    "att_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="근태기록ID"
                    ),
                ),
                ("work_dt", models.DateField(verbose_name="근무기준일")),
                (
                    "normal_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        verbose_name="정상근무",
                    ),
                ),
                (
                    "ot_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        verbose_name="잔업시간",
                    ),
                ),
                (
                    "weekend_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        verbose_name="토일근무",
                    ),
                ),
                (
                    "status_text",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="상태값"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        db_column="emp_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 근태 기록",
                "verbose_name_plural": "historical 근태 기록",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDepartment",
            fields=[
                (
                    "dept_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="부서코드"
                    ),
                ),
                (
                    "dept_comp",
                    models.CharField(max_length=100, verbose_name="소속회사명"),
                ),
                ("dept_nm", models.CharField(max_length=50, verbose_name="부서명")),
                ("in_use", models.BooleanField(default=True, verbose_name="사용여부")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_dept",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_dept_id",
                        db_constraint=False,
                        help_text="부서 안에 소속된 부서의 경우 이 컬럼을 사용합니다.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.department",
                        verbose_name="상위부서코드",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 부서 마스터",
                "verbose_name_plural": "historical 부서 마스터",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmployee",
            fields=[
                (
                    "emp_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="사원코드"
                    ),
                ),
                (
                    "emp_no",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="사원번호"
                    ),
                ),
                ("emp_nm", models.CharField(max_length=50, verbose_name="성명")),
                (
                    "emp_pos",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="직급"
                    ),
                ),
                (
                    "emp_type",
                    models.CharField(
                        choices=[
                            ("정규직", "정규직"),
                            ("계약직", "계약직"),
                            ("파트타임", "파트타임"),
                        ],
                        default="정규직",
                        max_length=30,
                        verbose_name="고용형태코드",
                    ),
                ),
                (
                    "emp_stat",
                    models.CharField(
                        choices=[
                            ("재직", "재직"),
                            ("휴직", "휴직"),
                            ("퇴직", "퇴직"),
                            ("정직", "정직"),
                        ],
                        default="재직",
                        max_length=30,
                        verbose_name="재직상태코드",
                    ),
                ),
                (
                    "emp_tel",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="연락처"
                    ),
                ),
                (
                    "emp_add",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="주소"
                    ),
                ),
                ("emp_hire", models.DateField(verbose_name="입사일")),
                (
                    "emp_retire_dt",
                    models.DateField(blank=True, null=True, verbose_name="퇴사일"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        blank=True,
                        db_column="dept_id",
                        db_constraint=False,
                        help_text="소속 부서 연결",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.department",
                        verbose_name="부서코드",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 사원 마스터",
                "verbose_name_plural": "historical 사원 마스터",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmployeeFinance",
            fields=[
                (
                    "bank_nm",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="은행명"
                    ),
                ),
                (
                    "bank_holder",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="예금주"
                    ),
                ),
                (
                    "has_car",
                    models.BooleanField(default=False, verbose_name="본인차량여부"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        db_column="emp_id",
                        db_constraint=False,
                        help_text="사원 1:1 연결",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 사원 금융 정보",
                "verbose_name_plural": "historical 사원 금융 정보",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLateRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                ("month", models.IntegerField(verbose_name="월")),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="지각 횟수"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        db_column="emp_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 지각 기록",
                "verbose_name_plural": "historical 지각 기록",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSalary",
            fields=[
                (
                    "salary_rec_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="급여 기록 ID"
                    ),
                ),
                (
                    "salary_month",
                    models.CharField(max_length=7, verbose_name="급여 귀속월"),
                ),
                (
                    "payment_dt",
                    models.DateField(blank=True, null=True, verbose_name="급여 지급일"),
                ),
                (
                    "base_amt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="기본급",
                    ),
                ),
                (
                    "pos_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="직책수당",
                    ),
                ),
                (
                    "exp_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="경력수당",
                    ),
                ),
                (
                    "weekly_holiday_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="주휴수당",
                    ),
                ),
                (
                    "ot_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="잔업시간(h)",
                    ),
                ),
                (
                    "ot_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="시간외수당",
                    ),
                ),
                (
                    "non_smoke_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="비흡연수당",
                    ),
                ),
                (
                    "func_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="업무기능수당",
                    ),
                ),
                (
                    "comm_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="통신보조비",
                    ),
                ),
                (
                    "special_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="특별수당",
                    ),
                ),
                (
                    "hourly_adj_amt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="시급정산",
                    ),
                ),
                (
                    "meal_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="식대비",
                    ),
                ),
                (
                    "car_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="자가운전보조금",
                    ),
                ),
                (
                    "income_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="갑근세",
                    ),
                ),
                (
                    "local_income_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="주민세",
                    ),
                ),
                (
                    "health_ins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="건강보험",
                    ),
                ),
                (
                    "national_pension",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="국민연금",
                    ),
                ),
                (
                    "emp_ins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="고용보험",
                    ),
                ),
                (
                    "longterm_care_ins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="노인장기요양보험",
                    ),
                ),
                (
                    "other_deduction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="기타공제",
                    ),
                ),
                (
                    "refund_amt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="환급금",
                    ),
                ),
                (
                    "health_ins_comp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="건강보험(회사)",
                    ),
                ),
                (
                    "pension_comp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="국민연금(회사)",
                    ),
                ),
                (
                    "emp_ins_comp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="고용보험(회사)",
                    ),
                ),
                (
                    "ind_acc_comp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="산재보험(회사)",
                    ),
                ),
                (
                    "total_gross_amt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="급여 총계",
                    ),
                ),
                (
                    "total_deduction_amt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="공제 총계",
                    ),
                ),
                (
                    "total_labor_cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="법인 인건비 총계",
                    ),
                ),
                (
                    "net_pay_amt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="실수령액",
                    ),
                ),
                (
                    "tax_free_exclusion",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="비과세 제외액",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        db_column="emp_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.employee",
                        verbose_name="사원 고유번호",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 급여 정보",
                "verbose_name_plural": "historical 급여 정보",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AttendanceRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                ("month", models.IntegerField(verbose_name="월")),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="비고"),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_remarks",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
            ],
            options={
                "verbose_name": "근태 비고",
                "verbose_name_plural": "근태 비고",
                "db_table": "hr_attendance_remark",
                "unique_together": {("emp", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "att_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="근태기록ID"
                    ),
                ),
                ("work_dt", models.DateField(verbose_name="근무기준일")),
                (
                    "normal_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        verbose_name="정상근무",
                    ),
                ),
                (
                    "ot_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        verbose_name="잔업시간",
                    ),
                ),
                (
                    "weekend_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=4,
                        verbose_name="토일근무",
                    ),
                ),
                (
                    "status_text",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="상태값"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
            ],
            options={
                "verbose_name": "근태 기록",
                "verbose_name_plural": "근태 기록",
                "db_table": "hr_attendance_log",
                "indexes": [
                    models.Index(fields=["emp", "work_dt"], name="idx_atndlog_emp_dt")
                ],
                "unique_together": {("emp", "work_dt")},
            },
        ),
        migrations.CreateModel(
            name="AnnualLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                (
                    "total_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="사용가능한연차(A)",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_leaves",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
            ],
            options={
                "verbose_name": "연차 관리",
                "verbose_name_plural": "연차 관리",
                "db_table": "hr_annual_leave",
                "unique_together": {("emp", "year")},
            },
        ),
        migrations.CreateModel(
            name="LateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                ("month", models.IntegerField(verbose_name="월")),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="지각 횟수"),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_records",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
            ],
            options={
                "verbose_name": "지각 기록",
                "verbose_name_plural": "지각 기록",
                "db_table": "hr_late_record",
                "unique_together": {("emp", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "salary_rec_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="급여 기록 ID"
                    ),
                ),
                (
                    "salary_month",
                    models.CharField(max_length=7, verbose_name="급여 귀속월"),
                ),
                (
                    "payment_dt",
                    models.DateField(blank=True, null=True, verbose_name="급여 지급일"),
                ),
                (
                    "base_amt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="기본급",
                    ),
                ),
                (
                    "pos_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="직책수당",
                    ),
                ),
                (
                    "exp_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="경력수당",
                    ),
                ),
                (
                    "weekly_holiday_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="주휴수당",
                    ),
                ),
                (
                    "ot_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="잔업시간(h)",
                    ),
                ),
                (
                    "ot_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="시간외수당",
                    ),
                ),
                (
                    "non_smoke_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="비흡연수당",
                    ),
                ),
                (
                    "func_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="업무기능수당",
                    ),
                ),
                (
                    "comm_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="통신보조비",
                    ),
                ),
                (
                    "special_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="특별수당",
                    ),
                ),
                (
                    "hourly_adj_amt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="시급정산",
                    ),
                ),
                (
                    "meal_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="식대비",
                    ),
                ),
                (
                    "car_allowance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="자가운전보조금",
                    ),
                ),
                (
                    "income_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="갑근세",
                    ),
                ),
                (
                    "local_income_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="주민세",
                    ),
                ),
                (
                    "health_ins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="건강보험",
                    ),
                ),
                (
                    "national_pension",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="국민연금",
                    ),
                ),
                (
                    "emp_ins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="고용보험",
                    ),
                ),
                (
                    "longterm_care_ins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="노인장기요양보험",
                    ),
                ),
                (
                    "other_deduction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="기타공제",
                    ),
                ),
                (
                    "refund_amt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="환급금",
                    ),
                ),
                (
                    "health_ins_comp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="건강보험(회사)",
                    ),
                ),
                (
                    "pension_comp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="국민연금(회사)",
                    ),
                ),
                (
                    "emp_ins_comp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="고용보험(회사)",
                    ),
                ),
                (
                    "ind_acc_comp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="산재보험(회사)",
                    ),
                ),
                (
                    "total_gross_amt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="급여 총계",
                    ),
                ),
                (
                    "total_deduction_amt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="공제 총계",
                    ),
                ),
                (
                    "total_labor_cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="법인 인건비 총계",
                    ),
                ),
                (
                    "net_pay_amt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="실수령액",
                    ),
                ),
                (
                    "tax_free_exclusion",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="비과세 제외액",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="hr.employee",
                        verbose_name="사원 고유번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "급여 정보",
                "verbose_name_plural": "급여 정보",
                "db_table": "hr_salary",
                "unique_together": {("emp", "salary_month")},
            },
        ),
    ]
