# Generated by Django 6.0.1 on 2026-03-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_stat",
            field=models.CharField(
                choices=[
                    ("재직", "재직"),
                    ("휴직", "휴직"),
                    ("퇴직", "퇴직"),
                    ("정직", "정직"),
                ],
                default="재직",
                max_length=30,
                verbose_name="재직상태코드",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_type",
            field=models.CharField(
                choices=[
                    ("정규직", "정규직"),
                    ("계약직", "계약직"),
                    ("파트타임", "파트타임"),
                ],
                default="정규직",
                max_length=30,
                verbose_name="고용형태코드",
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployee",
            name="emp_stat",
            field=models.CharField(
                choices=[
                    ("재직", "재직"),
                    ("휴직", "휴직"),
                    ("퇴직", "퇴직"),
                    ("정직", "정직"),
                ],
                default="재직",
                max_length=30,
                verbose_name="재직상태코드",
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployee",
            name="emp_type",
            field=models.CharField(
                choices=[
                    ("정규직", "정규직"),
                    ("계약직", "계약직"),
                    ("파트타임", "파트타임"),
                ],
                default="정규직",
                max_length=30,
                verbose_name="고용형태코드",
            ),
        ),
    ]
