# Generated by Django 6.0.1 on 2026-03-19 00:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_employee_emp_stat_alter_employee_emp_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLateRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="지각 횟수"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        db_column="emp_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 지각 기록",
                "verbose_name_plural": "historical 지각 기록",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="지각 횟수"),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_records",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
            ],
            options={
                "verbose_name": "지각 기록",
                "verbose_name_plural": "지각 기록",
                "db_table": "late_record",
                "unique_together": {("emp", "year")},
            },
        ),
    ]
