# Generated by Django 6.0.1 on 2026-03-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_late_record_add_month"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="annualleave",
            table="hr_annual_leave",
        ),
        migrations.AlterModelTable(
            name="attendancelog",
            table="hr_attendance_log",
        ),
        migrations.AlterModelTable(
            name="department",
            table="hr_department",
        ),
        migrations.AlterModelTable(
            name="employee",
            table="hr_employee",
        ),
        migrations.AlterModelTable(
            name="employeefinance",
            table="hr_employee_finance",
        ),
        migrations.AlterModelTable(
            name="laterecord",
            table="hr_late_record",
        ),
        migrations.AlterModelTable(
            name="salary",
            table="hr_salary",
        ),
        migrations.AlterModelTable(
            name="user",
            table="hr_user",
        ),
    ]
