# Generated by Django 6.0.1 on 2026-03-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_db_table_add_prefix"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(fields=["emp", "work_dt"], name="idx_atndlog_emp_dt"),
        ),
    ]
