# Generated by Django 6.0.1 on 2026-03-23 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_attendance_log_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연도")),
                ("month", models.IntegerField(verbose_name="월")),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="비고"),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_remarks",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
            ],
            options={
                "verbose_name": "근태 비고",
                "verbose_name_plural": "근태 비고",
                "db_table": "hr_attendance_remark",
                "unique_together": {("emp", "year", "month")},
            },
        ),
    ]
