# Generated by Django 6.0.1 on 2026-03-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_attendance_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsalary",
            name="refund_amt",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="환급금",
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="refund_amt",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="환급금",
            ),
        ),
    ]
