# Generated by Django 6.0.1 on 2026-03-16 23:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMaterial",
            fields=[
                (
                    "mat_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="자재 식별 PK"
                    ),
                ),
                (
                    "mat_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="사용자 지정 제품 코드",
                        max_length=50,
                        verbose_name="제품 코드",
                    ),
                ),
                (
                    "mat_nm",
                    models.CharField(
                        help_text="제품명", max_length=100, verbose_name="자재명"
                    ),
                ),
                (
                    "mat_maker",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="제조사"
                    ),
                ),
                (
                    "mat_spec",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="규격"
                    ),
                ),
                ("mat_unit", models.CharField(max_length=10, verbose_name="단위")),
                (
                    "mat_current_stock",
                    models.FloatField(default=0, verbose_name="현재재고"),
                ),
                (
                    "in_use",
                    models.BooleanField(
                        default=True,
                        help_text="자재 단종 시 FALSE",
                        verbose_name="사용여부",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 자재 마스터",
                "verbose_name_plural": "historical 자재 마스터",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "mat_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="자재 식별 PK"
                    ),
                ),
                (
                    "mat_code",
                    models.CharField(
                        blank=True,
                        help_text="사용자 지정 제품 코드",
                        max_length=50,
                        unique=True,
                        verbose_name="제품 코드",
                    ),
                ),
                (
                    "mat_nm",
                    models.CharField(
                        help_text="제품명", max_length=100, verbose_name="자재명"
                    ),
                ),
                (
                    "mat_maker",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="제조사"
                    ),
                ),
                (
                    "mat_spec",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="규격"
                    ),
                ),
                ("mat_unit", models.CharField(max_length=10, verbose_name="단위")),
                (
                    "mat_current_stock",
                    models.FloatField(default=0, verbose_name="현재재고"),
                ),
                (
                    "in_use",
                    models.BooleanField(
                        default=True,
                        help_text="자재 단종 시 FALSE",
                        verbose_name="사용여부",
                    ),
                ),
            ],
            options={
                "verbose_name": "자재 마스터",
                "verbose_name_plural": "자재 마스터",
                "db_table": "material",
                "unique_together": {("mat_nm", "mat_maker", "mat_spec")},
            },
        ),
        migrations.CreateModel(
            name="Inbound",
            fields=[
                (
                    "in_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="입고 기록 PK"
                    ),
                ),
                (
                    "in_purchase_dt",
                    models.DateField(verbose_name="영수증 상 실제 구매일"),
                ),
                (
                    "in_purchase_price",
                    models.FloatField(verbose_name="구매 당시 개당 단가"),
                ),
                ("in_qty", models.FloatField(verbose_name="입고된 수량")),
                (
                    "in_dtm",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="시스템 등록 시각"
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbounds",
                        to="hr.employee",
                        verbose_name="사원 코드 연결",
                    ),
                ),
                (
                    "mat",
                    models.ForeignKey(
                        db_column="mat_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbounds",
                        to="scm.material",
                        verbose_name="입고된 자재 연결",
                    ),
                ),
            ],
            options={
                "verbose_name": "입고 정보",
                "verbose_name_plural": "입고 정보",
                "db_table": "inbound",
            },
        ),
        migrations.CreateModel(
            name="Outbound",
            fields=[
                (
                    "out_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="출고기록 PK"
                    ),
                ),
                ("out_date", models.DateField(verbose_name="출고 일자")),
                ("out_qty", models.FloatField(verbose_name="사용/불출 수량")),
                (
                    "out_dtm",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="시스템 등록 시각"
                    ),
                ),
                (
                    "out_remark",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="emp_id",
                        help_text="출고를 기록한 사원의 정보. 실사용자는 비고에 기록",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbounds",
                        to="hr.employee",
                        verbose_name="사원코드",
                    ),
                ),
                (
                    "mat",
                    models.ForeignKey(
                        db_column="mat_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbounds",
                        to="scm.material",
                        verbose_name="자재 코드 연결",
                    ),
                ),
            ],
            options={
                "verbose_name": "출고 정보",
                "verbose_name_plural": "출고 정보",
                "db_table": "outbound",
            },
        ),
    ]
