# Generated by Django 6.0.1 on 2026-04-09 00:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "lot_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="LOT PK"
                    ),
                ),
                (
                    "lot_no",
                    models.CharField(
                        help_text="예: K40822-01", max_length=30, verbose_name="LOT No."
                    ),
                ),
                (
                    "lot_sub_no",
                    models.CharField(
                        blank=True,
                        help_text="예: -001, -003",
                        max_length=10,
                        null=True,
                        verbose_name="LOT 기번",
                    ),
                ),
                ("received_date", models.DateField(verbose_name="입고일")),
                (
                    "received_qty",
                    models.PositiveIntegerField(default=0, verbose_name="입고수량"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("INCOMING", "수입검사"), ("PROCESS", "공정")],
                        default="INCOMING",
                        max_length=10,
                        verbose_name="발생 구분",
                    ),
                ),
                (
                    "pd_nominal_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="PD 공칭값 (mm)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
            ],
            options={
                "verbose_name": "LOT",
                "verbose_name_plural": "LOT 목록",
                "db_table": "scm_lot",
                "ordering": ["-received_date", "lot_no"],
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "model_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="모델 PK"
                    ),
                ),
                (
                    "model_code",
                    models.CharField(
                        help_text="예: TP214N-AD-840UM, F84PC",
                        max_length=50,
                        unique=True,
                        verbose_name="모델 코드",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="모델명")),
                (
                    "product_group",
                    models.CharField(
                        choices=[
                            ("810", "T/A 810"),
                            ("840", "T/A 840"),
                            ("870", "T/A 870"),
                            ("920", "T/A 920"),
                        ],
                        help_text="T/A 종류 구분 (810 / 840 / 870 / 920)",
                        max_length=10,
                        verbose_name="제품 그룹",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="예: PEEK, PC",
                        max_length=50,
                        null=True,
                        verbose_name="소재",
                    ),
                ),
                (
                    "spec_description",
                    models.TextField(blank=True, null=True, verbose_name="규격 설명"),
                ),
                ("in_use", models.BooleanField(default=True, verbose_name="사용여부")),
            ],
            options={
                "verbose_name": "제품 모델",
                "verbose_name_plural": "제품 모델 마스터",
                "db_table": "scm_product_model",
                "ordering": ["product_group", "model_code"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProductModel",
            fields=[
                (
                    "model_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="모델 PK"
                    ),
                ),
                (
                    "model_code",
                    models.CharField(
                        db_index=True,
                        help_text="예: TP214N-AD-840UM, F84PC",
                        max_length=50,
                        verbose_name="모델 코드",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="모델명")),
                (
                    "product_group",
                    models.CharField(
                        choices=[
                            ("810", "T/A 810"),
                            ("840", "T/A 840"),
                            ("870", "T/A 870"),
                            ("920", "T/A 920"),
                        ],
                        help_text="T/A 종류 구분 (810 / 840 / 870 / 920)",
                        max_length=10,
                        verbose_name="제품 그룹",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="예: PEEK, PC",
                        max_length=50,
                        null=True,
                        verbose_name="소재",
                    ),
                ),
                (
                    "spec_description",
                    models.TextField(blank=True, null=True, verbose_name="규격 설명"),
                ),
                ("in_use", models.BooleanField(default=True, verbose_name="사용여부")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 제품 모델",
                "verbose_name_plural": "historical 제품 모델 마스터",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="IncomingInspection",
            fields=[
                (
                    "inspection_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="검사 PK"
                    ),
                ),
                ("inspection_date", models.DateField(verbose_name="검사일")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "합격"),
                            ("FAIL", "불합격"),
                            ("PENDING", "보류"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="검사 결과",
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="보고서 번호"
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(
                        blank=True,
                        help_text="예: 수입검사 커팅 불량, Back PAD 코팅액 묻음",
                        max_length=200,
                        null=True,
                        verbose_name="부적합 내용",
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True,
                        help_text="예: 재작업 후 입고 (2025-02-07) / EG개선품",
                        null=True,
                        verbose_name="조치 내용",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        db_column="lot_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_inspection",
                        to="scm.lot",
                        verbose_name="LOT",
                    ),
                ),
            ],
            options={
                "verbose_name": "수입검사",
                "verbose_name_plural": "수입검사 목록",
                "db_table": "scm_incoming_inspection",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalNonConformance",
            fields=[
                (
                    "nc_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="부적합 PK"
                    ),
                ),
                (
                    "nc_type",
                    models.CharField(
                        choices=[
                            ("INCOMING", "수입검사 부적합"),
                            ("PROCESS", "공정 부적합"),
                            ("IC_PROCESS", "IC 공정 부적합"),
                        ],
                        max_length=15,
                        verbose_name="부적합 유형",
                    ),
                ),
                (
                    "detection_stage",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="발견 단계"
                    ),
                ),
                (
                    "defect_description",
                    models.TextField(
                        help_text="예: 이형지 손상, Back PAD 코팅액 묻음",
                        verbose_name="부적합 내용",
                    ),
                ),
                (
                    "corrective_action",
                    models.TextField(blank=True, null=True, verbose_name="시정 조치"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DETECTED", "발생"),
                            ("WAITING_RETURN", "반송 대기"),
                            ("RETURN_COMPLETED", "반송 완료"),
                            ("REWORK_IN_PROGRESS", "재작업 중"),
                            ("REWORK_COMPLETED", "재작업 완료"),
                            ("IN_HOUSE_STORAGE", "사내 보관"),
                            ("USED_UP", "사용 완료"),
                            ("DISCARDED", "폐기"),
                            ("TEST_IN_PROGRESS", "테스트 중"),
                        ],
                        db_index=True,
                        default="DETECTED",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "return_date",
                    models.DateField(blank=True, null=True, verbose_name="반송 완료일"),
                ),
                (
                    "rework_complete_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="재작업 완료일"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="등록일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일시"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        db_column="lot_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="scm.lot",
                        verbose_name="LOT",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 부적합품",
                "verbose_name_plural": "historical 부적합품 목록",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalIncomingInspection",
            fields=[
                (
                    "inspection_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="검사 PK"
                    ),
                ),
                ("inspection_date", models.DateField(verbose_name="검사일")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "합격"),
                            ("FAIL", "불합격"),
                            ("PENDING", "보류"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="검사 결과",
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="보고서 번호"
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(
                        blank=True,
                        help_text="예: 수입검사 커팅 불량, Back PAD 코팅액 묻음",
                        max_length=200,
                        null=True,
                        verbose_name="부적합 내용",
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True,
                        help_text="예: 재작업 후 입고 (2025-02-07) / EG개선품",
                        null=True,
                        verbose_name="조치 내용",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="등록일시"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        db_column="lot_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="scm.lot",
                        verbose_name="LOT",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 수입검사",
                "verbose_name_plural": "historical 수입검사 목록",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LotDefectSummary",
            fields=[
                (
                    "summary_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="집계 PK"
                    ),
                ),
                (
                    "incoming_defect_qty",
                    models.PositiveIntegerField(
                        default=0, verbose_name="수입불량 수량"
                    ),
                ),
                (
                    "process_defect_qty",
                    models.PositiveIntegerField(
                        default=0, verbose_name="공정불량 수량"
                    ),
                ),
                (
                    "rework_qty",
                    models.PositiveIntegerField(default=0, verbose_name="재작업 수량"),
                ),
                (
                    "pending_qty",
                    models.PositiveIntegerField(default=0, verbose_name="대기 수량"),
                ),
                (
                    "return_complete_qty",
                    models.PositiveIntegerField(
                        default=0, verbose_name="반송 완료 수량"
                    ),
                ),
                (
                    "defect_lot_sub_nos",
                    models.TextField(
                        blank=True,
                        help_text="예: 065, 076, 191, 407",
                        null=True,
                        verbose_name="불량 기번 목록",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최종 수정일시"),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        db_column="lot_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_summary",
                        to="scm.lot",
                        verbose_name="LOT",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOT 불량 집계",
                "verbose_name_plural": "LOT 불량 집계",
                "db_table": "scm_lot_defect_summary",
            },
        ),
        migrations.CreateModel(
            name="LotMeasurement",
            fields=[
                (
                    "measurement_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="측정 PK"
                    ),
                ),
                (
                    "measurement_type",
                    models.CharField(
                        choices=[("PD", "PD 측정 (두께)"), ("CS", "CS 측정 (간격)")],
                        max_length=5,
                        verbose_name="측정 유형",
                    ),
                ),
                ("shipping_date", models.DateField(verbose_name="출하일")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="출하 수량 (pcs)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        db_column="lot_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurements",
                        to="scm.lot",
                        verbose_name="LOT",
                    ),
                ),
            ],
            options={
                "verbose_name": "LOT 측정 헤더",
                "verbose_name_plural": "LOT 측정 헤더 목록",
                "db_table": "scm_lot_measurement",
                "ordering": ["-shipping_date", "lot"],
                "unique_together": {("lot", "measurement_type", "shipping_date")},
            },
        ),
        migrations.CreateModel(
            name="NonConformance",
            fields=[
                (
                    "nc_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="부적합 PK"
                    ),
                ),
                (
                    "nc_type",
                    models.CharField(
                        choices=[
                            ("INCOMING", "수입검사 부적합"),
                            ("PROCESS", "공정 부적합"),
                            ("IC_PROCESS", "IC 공정 부적합"),
                        ],
                        max_length=15,
                        verbose_name="부적합 유형",
                    ),
                ),
                (
                    "detection_stage",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="발견 단계"
                    ),
                ),
                (
                    "defect_description",
                    models.TextField(
                        help_text="예: 이형지 손상, Back PAD 코팅액 묻음",
                        verbose_name="부적합 내용",
                    ),
                ),
                (
                    "corrective_action",
                    models.TextField(blank=True, null=True, verbose_name="시정 조치"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DETECTED", "발생"),
                            ("WAITING_RETURN", "반송 대기"),
                            ("RETURN_COMPLETED", "반송 완료"),
                            ("REWORK_IN_PROGRESS", "재작업 중"),
                            ("REWORK_COMPLETED", "재작업 완료"),
                            ("IN_HOUSE_STORAGE", "사내 보관"),
                            ("USED_UP", "사용 완료"),
                            ("DISCARDED", "폐기"),
                            ("TEST_IN_PROGRESS", "테스트 중"),
                        ],
                        db_index=True,
                        default="DETECTED",
                        max_length=20,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "return_date",
                    models.DateField(blank=True, null=True, verbose_name="반송 완료일"),
                ),
                (
                    "rework_complete_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="재작업 완료일"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        db_column="lot_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nonconformances",
                        to="scm.lot",
                        verbose_name="LOT",
                    ),
                ),
            ],
            options={
                "verbose_name": "부적합품",
                "verbose_name_plural": "부적합품 목록",
                "db_table": "scm_nonconformance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NCStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DETECTED", "발생"),
                            ("WAITING_RETURN", "반송 대기"),
                            ("RETURN_COMPLETED", "반송 완료"),
                            ("REWORK_IN_PROGRESS", "재작업 중"),
                            ("REWORK_COMPLETED", "재작업 완료"),
                            ("IN_HOUSE_STORAGE", "사내 보관"),
                            ("USED_UP", "사용 완료"),
                            ("DISCARDED", "폐기"),
                            ("TEST_IN_PROGRESS", "테스트 중"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="이전 상태",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("DETECTED", "발생"),
                            ("WAITING_RETURN", "반송 대기"),
                            ("RETURN_COMPLETED", "반송 완료"),
                            ("REWORK_IN_PROGRESS", "재작업 중"),
                            ("REWORK_COMPLETED", "재작업 완료"),
                            ("IN_HOUSE_STORAGE", "사내 보관"),
                            ("USED_UP", "사용 완료"),
                            ("DISCARDED", "폐기"),
                            ("TEST_IN_PROGRESS", "테스트 중"),
                        ],
                        max_length=20,
                        verbose_name="변경 후 상태",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        help_text="예: Fujibo 社 반송 완료 (2024-12-26)",
                        null=True,
                        verbose_name="변경 사유",
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="변경자"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="변경일시"),
                ),
                (
                    "nc",
                    models.ForeignKey(
                        db_column="nc_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_histories",
                        to="scm.nonconformance",
                        verbose_name="부적합품",
                    ),
                ),
            ],
            options={
                "verbose_name": "부적합 상태 이력",
                "verbose_name_plural": "부적합 상태 이력",
                "db_table": "scm_nc_status_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddField(
            model_name="lot",
            name="product_model",
            field=models.ForeignKey(
                db_column="model_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="scm.productmodel",
                verbose_name="제품 모델",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLot",
            fields=[
                (
                    "lot_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="LOT PK"
                    ),
                ),
                (
                    "lot_no",
                    models.CharField(
                        help_text="예: K40822-01", max_length=30, verbose_name="LOT No."
                    ),
                ),
                (
                    "lot_sub_no",
                    models.CharField(
                        blank=True,
                        help_text="예: -001, -003",
                        max_length=10,
                        null=True,
                        verbose_name="LOT 기번",
                    ),
                ),
                ("received_date", models.DateField(verbose_name="입고일")),
                (
                    "received_qty",
                    models.PositiveIntegerField(default=0, verbose_name="입고수량"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("INCOMING", "수입검사"), ("PROCESS", "공정")],
                        default="INCOMING",
                        max_length=10,
                        verbose_name="발생 구분",
                    ),
                ),
                (
                    "pd_nominal_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="PD 공칭값 (mm)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="등록일시"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        blank=True,
                        db_column="model_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="scm.productmodel",
                        verbose_name="제품 모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical LOT",
                "verbose_name_plural": "historical LOT 목록",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MeasurementItem",
            fields=[
                (
                    "item_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="측정 항목 PK"
                    ),
                ),
                (
                    "sequence_no",
                    models.PositiveSmallIntegerField(
                        help_text="엑셀 No 열 값", verbose_name="순번"
                    ),
                ),
                (
                    "lot_sub_no",
                    models.CharField(
                        blank=True,
                        help_text="예: -001, -003",
                        max_length=10,
                        null=True,
                        verbose_name="LOT 기번",
                    ),
                ),
                (
                    "meas_1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="측정1",
                    ),
                ),
                (
                    "meas_2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="측정2",
                    ),
                ),
                (
                    "meas_3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="측정3",
                    ),
                ),
                (
                    "meas_4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="측정4",
                    ),
                ),
                (
                    "average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="평균",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        db_column="measurement_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="scm.lotmeasurement",
                        verbose_name="측정 헤더",
                    ),
                ),
            ],
            options={
                "verbose_name": "측정 항목",
                "verbose_name_plural": "측정 항목 목록",
                "db_table": "scm_measurement_item",
                "ordering": ["measurement", "sequence_no"],
                "unique_together": {("measurement", "sequence_no")},
            },
        ),
        migrations.AddIndex(
            model_name="nonconformance",
            index=models.Index(fields=["status"], name="idx_nc_status"),
        ),
        migrations.AddIndex(
            model_name="nonconformance",
            index=models.Index(fields=["nc_type"], name="idx_nc_type"),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(fields=["lot_no"], name="idx_lot_lot_no"),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(fields=["received_date"], name="idx_lot_recv_dt"),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(fields=["product_model"], name="idx_lot_model"),
        ),
        migrations.AlterUniqueTogether(
            name="lot",
            unique_together={("lot_no", "lot_sub_no")},
        ),
    ]
