# Generated by Django 6.0.1 on 2026-03-17 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incoming_date", models.DateField(unique=True, verbose_name="입고일")),
            ],
            options={
                "verbose_name": "입고검사",
                "verbose_name_plural": "입고검사 목록",
                "ordering": ["-incoming_date"],
            },
        ),
        migrations.CreateModel(
            name="TA_management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="LOT NO."
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="수량"),
                ),
                (
                    "incoming_defect",
                    models.PositiveIntegerField(default=0, verbose_name="수입불량"),
                ),
                ("defect", models.PositiveIntegerField(default=0, verbose_name="불량")),
                (
                    "rework",
                    models.PositiveIntegerField(default=0, verbose_name="재작업"),
                ),
                (
                    "pending",
                    models.PositiveIntegerField(default=0, verbose_name="대기"),
                ),
                (
                    "incoming_inspection_defect",
                    models.TextField(
                        blank=True, default="", verbose_name="수입검사불량"
                    ),
                ),
                (
                    "process_defect",
                    models.TextField(blank=True, default="", verbose_name="공정불량"),
                ),
                (
                    "pending_detail",
                    models.TextField(blank=True, default="", verbose_name="대기 상세"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="비고")),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="scm.incominginspection",
                        verbose_name="입고검사",
                    ),
                ),
            ],
            options={
                "verbose_name": "TA 관리",
                "verbose_name_plural": "TA 관리 목록",
                "ordering": ["lot_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inspection", "lot_number"),
                        name="unique_lot_per_inspection",
                    )
                ],
            },
        ),
    ]
