# Generated by Django 6.0.1 on 2026-03-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm", "0002_incominginspection_ta_management"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TA_management",
            new_name="TAManagement",
        ),
        migrations.AlterField(
            model_name="historicalmaterial",
            name="mat_current_stock",
            field=models.DecimalField(max_digits=15, decimal_places=3, default=0, verbose_name="현재재고"),
        ),
        migrations.AlterField(
            model_name="inbound",
            name="in_purchase_price",
            field=models.DecimalField(max_digits=15, decimal_places=2, verbose_name="구매 당시 개당 단가"),
        ),
        migrations.AlterField(
            model_name="inbound",
            name="in_qty",
            field=models.DecimalField(max_digits=15, decimal_places=3, verbose_name="입고된 수량"),
        ),
        migrations.AlterField(
            model_name="material",
            name="mat_current_stock",
            field=models.DecimalField(max_digits=15, decimal_places=3, default=0, verbose_name="현재재고"),
        ),
        migrations.AlterField(
            model_name="outbound",
            name="out_qty",
            field=models.DecimalField(max_digits=15, decimal_places=3, verbose_name="사용/불출 수량"),
        ),
        migrations.AlterModelTable(
            name="tamanagement",
            table="scm_ta_management",
        ),
    ]
