# Generated by Django 6.0.1 on 2026-03-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scm", "0003_rename_ta_management_to_tamanagement"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="inbound",
            table="scm_inbound",
        ),
        migrations.AlterModelTable(
            name="material",
            table="scm_material",
        ),
        migrations.AlterModelTable(
            name="outbound",
            table="scm_outbound",
        ),
    ]
