# Generated by Django 6.0.1 on 2026-03-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scm", "0004_db_table_add_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbound",
            name="in_purchase_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="구매 당시 개당 단가"
            ),
        ),
        migrations.AlterField(
            model_name="inbound",
            name="in_qty",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="입고된 수량"
            ),
        ),
        migrations.AlterField(
            model_name="outbound",
            name="out_qty",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="사용/불출 수량"
            ),
        ),
    ]
