# Generated by Django 6.0.1 on 2026-03-31 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scm", "0005_decimal_max_digits_adjust"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbound",
            name="emp",
        ),
        migrations.RemoveField(
            model_name="inbound",
            name="mat",
        ),
        migrations.AlterUniqueTogether(
            name="material",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="outbound",
            name="mat",
        ),
        migrations.RemoveField(
            model_name="outbound",
            name="emp",
        ),
        migrations.DeleteModel(
            name="HistoricalMaterial",
        ),
        migrations.DeleteModel(
            name="Inbound",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="Outbound",
        ),
    ]
