# Generated by Django 6.0.1 on 2026-05-06 04:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True, verbose_name="적용 연도")),
                (
                    "health_ins_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=3.545,
                        max_digits=6,
                        verbose_name="건강보험요율-직원(%)",
                    ),
                ),
                (
                    "longterm_care_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=12.95,
                        max_digits=6,
                        verbose_name="노인장기요양요율(건강보험료 기준 %)",
                    ),
                ),
                (
                    "pension_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.5,
                        max_digits=5,
                        verbose_name="국민연금요율-직원(%)",
                    ),
                ),
                (
                    "emp_ins_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.9,
                        max_digits=5,
                        verbose_name="고용보험요율-직원(%)",
                    ),
                ),
                (
                    "health_ins_rate_comp",
                    models.DecimalField(
                        decimal_places=3,
                        default=3.545,
                        max_digits=6,
                        verbose_name="건강보험요율-회사(%)",
                    ),
                ),
                (
                    "longterm_care_rate_comp",
                    models.DecimalField(
                        decimal_places=3,
                        default=12.95,
                        max_digits=6,
                        verbose_name="노인장기요양요율-회사(건강보험료 기준 %)",
                    ),
                ),
                (
                    "pension_rate_comp",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.5,
                        max_digits=5,
                        verbose_name="국민연금요율-회사(%)",
                    ),
                ),
                (
                    "emp_ins_rate_comp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.9,
                        max_digits=5,
                        verbose_name="고용보험요율-회사(%)",
                    ),
                ),
                (
                    "ind_acc_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.73,
                        max_digits=5,
                        verbose_name="산재보험요율-회사(%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "연도별 급여 요율",
                "verbose_name_plural": "연도별 급여 요율",
                "db_table": "tax_salary_rate",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSalaryRate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField(db_index=True, verbose_name="적용 연도")),
                (
                    "health_ins_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=3.545,
                        max_digits=6,
                        verbose_name="건강보험요율-직원(%)",
                    ),
                ),
                (
                    "longterm_care_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=12.95,
                        max_digits=6,
                        verbose_name="노인장기요양요율(건강보험료 기준 %)",
                    ),
                ),
                (
                    "pension_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.5,
                        max_digits=5,
                        verbose_name="국민연금요율-직원(%)",
                    ),
                ),
                (
                    "emp_ins_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.9,
                        max_digits=5,
                        verbose_name="고용보험요율-직원(%)",
                    ),
                ),
                (
                    "health_ins_rate_comp",
                    models.DecimalField(
                        decimal_places=3,
                        default=3.545,
                        max_digits=6,
                        verbose_name="건강보험요율-회사(%)",
                    ),
                ),
                (
                    "longterm_care_rate_comp",
                    models.DecimalField(
                        decimal_places=3,
                        default=12.95,
                        max_digits=6,
                        verbose_name="노인장기요양요율-회사(건강보험료 기준 %)",
                    ),
                ),
                (
                    "pension_rate_comp",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.5,
                        max_digits=5,
                        verbose_name="국민연금요율-회사(%)",
                    ),
                ),
                (
                    "emp_ins_rate_comp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.9,
                        max_digits=5,
                        verbose_name="고용보험요율-회사(%)",
                    ),
                ),
                (
                    "ind_acc_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.73,
                        max_digits=5,
                        verbose_name="산재보험요율-회사(%)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 연도별 급여 요율",
                "verbose_name_plural": "historical 연도별 급여 요율",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
