# Generated by Django 6.0.1 on 2026-03-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="salaryrate",
            table="tax_salary_rate",
        ),
    ]
