# Generated by Django 6.0.1 on 2026-03-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0003_add_company_rate_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsalaryrate",
            name="min_hourly_wage",
        ),
        migrations.RemoveField(
            model_name="historicalsalaryrate",
            name="work_hours_monthly",
        ),
        migrations.RemoveField(
            model_name="salaryrate",
            name="min_hourly_wage",
        ),
        migrations.RemoveField(
            model_name="salaryrate",
            name="work_hours_monthly",
        ),
    ]
