# Generated by Django 6.0.1 on 2026-03-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0005_salary_formula"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalaryFormula",
        ),
    ]
