# Generated by Django 6.0.1 on 2026-05-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "작성"),
                            ("UPDATE", "수정"),
                            ("DELETE", "삭제"),
                            ("LOGIN", "로그인"),
                            ("LOGOUT", "로그아웃"),
                        ],
                        max_length=10,
                        verbose_name="작업 유형",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="카테고리")),
                (
                    "target_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="대상 명칭"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, null=True, verbose_name="변경 내역"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="작업 일시"),
                ),
            ],
            options={
                "verbose_name": "작업 로그",
                "verbose_name_plural": "작업 로그 목록",
                "ordering": ["-timestamp"],
            },
        ),
    ]
